version: '3.9'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - ./local-files:/home/node/.n8n
      - n8n_data:/home/node/.n8n/data
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USERNAME=devs
      - N8N_BASIC_AUTH_PASSWORD=@GS123vp
    networks:
      - traefik_proxy

  traefik:
    image: traefik:v2.9
    restart: always
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=engineersinprogress071116@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_letsencrypt:/letsencrypt
    networks:
      - traefik_proxy

volumes:
  n8n_data:
  traefik_letsencrypt:

networks:
  traefik_proxy:
    external: true